coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        paths: ["!test/"]  # remove all files in ""

